### ISSUE TITLE
not receiving any toot

### ISSUE THREAD

**Issue by taraletti** [halcy/Mastodon.py#271] opened 2022-11-21 11:54 UTC
Hi guys, I'm using this wrapper with a Delta chat bot, and I'm not receiving any toot. I can send... This is the error

`  ❌ ERROR while checking your account: Could not parse response as JSON, response code was 200, bad json content was 'b'[{"account":{"acct":"spectrumgirl@xarxa.cloud","avatar":"https://stereophonic.space/proxy/F0N-iwKv-nXDltaLfciAbjc6w-A/aHR0cHM6Ly94YXJ4YS5jbG91ZC9zeXN0ZW0vYWNjb3VudHMvYXZhdGFycy8wMDAvMDI4LzAwNC9vcmlnaW5hbC84MzZmMjNmMTI1NWVhMjJmLnBuZw/836f23f1255ea22f.png","avatar_static":"https://stereophonic.space/proxy/F0N-iwKv-nXDltaLfciAbjc6w-A/aHR0cHM6Ly94YXJ4YS5jbG91ZC9zeXN0ZW0vYWNjb3VudHMvYXZhdGFycy8wMDAvMDI4LzAwNC9vcmlnaW5hbC84MzZmMjNmMTI1NWVhMjJmLnBuZw/836f23f1255ea22f.png","bot":false,"created_at":"2021-03-14T19:11:18.000Z","display_name":"spectrumGirl (she/her) \xf0\x9f\x91\xa9\xe2\x80\x8d\xf0\x9f\x92\xbb\xf0\x9f\xa5\x87","emojis":[],"fields":[],"followers_count":778,"following_count":276,"fqn":"spectrumgirl@xarxa.cloud","header":"https://stereophonic.space/proxy/xUGUEWxh0Z8pu4dTroWOsI8FLmw/aHR0cHM6Ly94YXJ4YS5jbG91ZC9zeXN0ZW0vYWNjb3VudHMvaGVhZGVycy8wMDAvMDI4LzAwNC9vcmlnaW5hbC84ODhjYjIzMjJkOGY0MzAxLnBuZw/888cb2322d8f4301.png","header_static":"https://stereophonic.space/proxy/xUGUEWxh0Z8pu4dTroWOsI8FLmw/aHR0cHM6Ly94YXJ4YS5jbG91ZC9zeXN0ZW0vYWNjb3VudHMvaGVhZGVycy8wMDAvMDI4LzAwNC9vcmlnaW5hbC84ODhjYjIzMjJkOGY0MzAxLnBuZw/888cb2322d8f4301.png","id":"A5D549glHox0X1ItgO","locked":false,"note":"<p>SpectrumGirl  \xf0\x9f\xa7\x9c\xe2\x80\x8d\xe2\x99\x80\xef\xb8\x8f<br/>( \xcb\x98 \xc2\xb3\xcb\x98)\xe2\x99\xa5 </p><p>Educadora Social  y  Desarrolladora </p><p>Diversidad y Tecnolog\xc3\xada \xf0\x9f\x92\x9e</p><p>Moderadora de <a href=\\"https://xarxa.cloud/tags/xarxaCloud\\" rel=\\"tag\\">#<span>xarxaCloud</span></a><br/>Pertenezco al colectivo de <a href=\\"https://xarxa.cloud/tags/fediverseTV\\" rel=\\"tag\\">#<span>fediverseTV</span></a></p>","pleroma":{"accepts_chat_messages":null,"also_known_as":[],"ap_id":"https://xarxa.cloud/users/spectrumgirl","background_image":null,"favicon":"https://stereophonic.space/proxy/RL9sdydLC_c58P5QE48r59D4wsI/aHR0cHM6Ly94YXJ4YS5jbG91ZC9mYXZpY29uLmljbw/favicon.ico","hide_favorites":true,"hide_followers":false,"hide_followers_count":false,"hide_follows":false,"hide_follows_count":false,"is_admin":false,"is_confirmed":true,"is_moderator":false,"relationship":{},"skip_thread_containment":false,"tags":[]},"source":{"fields":[],"note":"","pleroma":{"actor_type":"Person","discoverable":false},"sensitive":false},"statuses_count":449,"url":"https://xarxa.cloud/@spectrumgirl","username":"spectrumgirl"},"application":null,"bookmarked":false,"card":null,"content":"<p><span class=\\"h-card\\"><a href=\\"https://mastodon.lol/@tinyampi\\" class=\\"u-url mention\\">@<span>tinyampi</span></a></span> yeaahh ya ense\xc3\xb1ar\xc3\xa1s! :ablobcatattention:</p>","created_at":"2022-11-19T13:57:57.000Z","emojis":[{"shortcode":"ablobcatattention","static_url":"https://stereophonic.space/proxy/8agnQ7Mamk_u0N2FwRRkOR2T5e0/aHR0cHM6Ly94YXJ4YS5jbG91ZC9zeXN0ZW0vY3VzdG9tX2Vtb2ppcy9pbWFnZXMvMDAwLzAyMS8yMDYvb3JpZ2luYWwvOWY2MDZjMGNkNmVhM2M3Yy5wbmc/9f606c0cd6ea3c7c.png","url":"https://stereophonic.space/proxy/8agnQ7Mamk_u0N2FwRRkOR2T5e0/aHR0cHM6Ly94YXJ4YS5jbG91ZC9zeXN0ZW0vY3VzdG9tX2Vtb2ppcy9pbWFnZXMvMDAwLzAyMS8yMDYvb3JpZ2luYWwvOWY2MDZjMGNkNmVhM2M3Yy5wbmc/9f606c0cd6ea3c7c.png","visible_in_picker":false}],"favourited":false,"favourites_count":0,"id":"APlP6YxtuqEwk9wIkK","in_reply_to_account_id":"APlOQyE1bpk0vKeGK8","in_reply_to_id":"APlOz4phY3yrGMXCXw","language":null,"media_attachments":[],"mentions":[{"acct":"tinyampi@mastodon.lol","id":"APlOQyE1bpk0vKeGK8","url":"https://mastodon.lol/@tinyampi","username":"tinyampi"}],"muted":false,"pinned":false,"pleroma":{"content":{"text/plain":"@tinyampi yeaahh ya ense\xc3\xb1ar\xc3\xa1s! [...] `

**Comment by halcy** [comment] 2022-11-21 13:12
That's interesting and weird. Somehow, the json does not parse, which should very much NOT happen, and would indicate a bug in either pythons json parser, or mastodons json output generation (or a local misconfiguration). Can you tell me what server you are on?

**Comment by halcy** [comment] 2022-11-21 13:15
Ideally, I'd like to get some output for debugging. If it still happens for you, I can send you a snippet that you could run that should get me the info I need to dig into this (after I get off work), if you'd be willing to help with that.

**Comment by taraletti** [comment] 2022-11-21 14:23
> That's interesting and weird. Somehow, the json does not parse, which should very much NOT happen, and would indicate a bug in either pythons json parser, or mastodons json output generation (or a local misconfiguration). Can you tell me what server you are on?

Well, it's not a bot I set up. And it isn't a Mastodon account either, it's a Pleroma account . Somehow managed to log in and was working quite well with my previous instance, same to Friendica. But in the last week I began to receive those errors

**Comment by taraletti** [comment] 2022-11-21 14:24
> Ideally, I'd like to get some output for debugging. If it still happens for you, I can send you a snippet that you could run that should get me the info I need to dig into this (after I get off work), if you'd be willing to help with that.

As I tell you, didn't set up the bot. Is there any other way to collaborate?

**Comment by taraletti** [comment] 2022-11-21 14:34
And on Friendica I get this

` ❌ ERROR while checking your account: ('Mastodon API returned error', 404, 'Not Found', 'Endpoint not found.') `

**Comment by halcy** [comment] 2022-11-21 14:59
Ah, hm. Generally, Pleroma and Friendica and other-non-masto account support tends to be a bit spotty, and I don't really unit test or even manually try it, so it's possible a Mastodon.py update changed something and it broke. I do want to support them, though. For the JSON error, I can probably still send you some code (if you're able to run it) that will log in and try to fetch the same thing and, if it breaks, give me better info to diagnose with and then to either fix on my side of forward to Pleroma so they can fix it. For the Friendica thing, I'd have to know what endpoint it's trying to actually use, which unfortunately I did not put into the error message. Do you know who runs the bot, or if I can find the source somewhere?

**Comment by halcy** [comment] 2022-11-21 15:38
So, if you have the ability, run this:

```
from mastodon import Mastodon
import pickle

PLEROMA_URL = "https://yourpleromaurl"
EMAIL = "your@email.com"
PASSWORD = "yourpassword"

Mastodon.create_app('pytooterapp', api_base_url = PLEROMA_URL, to_file = 'client_credential_DO_NOT_SHARE.secret')
client_unauthed = Mastodon(client_id = 'client_credential_DO_NOT_SHARE.secret')
client_unauthed.log_in(EMAIL, PASSWORD, to_file = 'user_credential_DO_NOT_SHARE.secret')
client = Mastodon(access_token = 'user_credential_DO_NOT_SHARE.secret', debug_requests=True)
try:
    pickle.dump(client.account_search("spectrumgirl@xarxa.cloud"), open("output.pkl", 'wb'))
except Exception as e:
    print(e)
client.revoke_access_token()
```

Prefereably with a recent Mastodon.py version installed. It should print an error. If it does not: Then no idea what broke, and we can probably stop there. After, share with me the console output, **PRIVATELY** (lorenzd@gmail.com). That last part is important, since the debug output contains an access token that will let people access your account. The code does try to revoke it, but not sure if that will work on Pleroma, so better not risk it. You can also check in pleroma UI somewhere and revoke it manually, probably. I promise I will not do anything except try to debug, though fully understand if you're not comfortable with that anyways - in that case, I'll try to find a Pleroma instance I can test this on.

**Comment by adbenitez** [comment] 2022-11-21 22:06
hi @halcy, I am the admin&creator of the [bot/bridge](https://github.com/simplebot-org/simplebot_mastodon) @taraletti is using, thanks a lot for your work and interest to help!

I have just created an account in a Pleroma server (https://stereophonic.space that, reading the log posted here by @taraletti, seems to be the server he is using) to run your script, here is the output:

[log.txt](https://github.com/halcy/Mastodon.py/files/10060944/log.txt)

all seems fine except a bug(?) in  `client.revoke_access_token()` call at the end of the script:

```
Traceback (most recent call last):
  File "masto.py", line 25, in <module>
    client.revoke_access_token()
  File "/home/dc/.venv/main/lib/python3.8/site-packages/mastodon/Mastodon.py", line 649, in revoke_access_token
    raise MastodonIllegalArgumentError("Client authentication (id + secret) is required to revoke tokens.")
mastodon.Mastodon.MastodonIllegalArgumentError: Client authentication (id + secret) is required to revoke tokens.
```

**Comment by adbenitez** [comment] 2022-11-21 22:14
reading the bot logs I found the full stacktrace which seems to point an issue in parsing a date field:

```
Traceback (most recent call last):
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/mastodon/Mastodon.py", line 3219, in __json_date_parse
    json_object[k] = dateutil.parser.parse(v)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 652, in parse
    raise ParserError("String does not contain a date: %s", timestr)
dateutil.parser._parser.ParserError: String does not contain a date: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/mastodon/Mastodon.py", line 3433, in __api_request
    response = response_object.json(object_hook=self.__json_hooks)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/mastodon/Mastodon.py", line 3257, in __json_hooks
    json_object = Mastodon.__json_date_parse(json_object)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/mastodon/Mastodon.py", line 3221, in __json_date_parse
    raise MastodonAPIError('Encountered invalid date.')
mastodon.Mastodon.MastodonAPIError: Encountered invalid date.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/simplebot_mastodon/util.py", line 280, in listen_to_mastodon
    _check_home(bot, masto, addr, home_chat, last_home)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/simplebot_mastodon/util.py", line 525, in _check_home
    toots = masto.timeline_home(min_id=last_id, limit=100)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/mastodon/Mastodon.py", line 102, in wrapper
    return function(self, *args, **kwargs)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/mastodon/Mastodon.py", line 744, in timeline_home
    since_id=since_id, limit=limit)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/mastodon/Mastodon.py", line 102, in wrapper
    return function(self, *args, **kwargs)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/mastodon/Mastodon.py", line 734, in timeline
    return self.__api_request('GET', url, params)
  File "/home/adb/.venv/simplebot%40testrun.org/lib/python3.7/site-packages/mastodon/Mastodon.py", line 3438, in __api_request
    response_object.content))
mastodon.Mastodon.MastodonAPIError: Could not parse response as JSON, response code was 200, bad json content was 'b'[{"account":{"acct":"spectrumgirl@xarxa.cloud","a[...]
```

**Comment by halcy** [comment] 2022-11-21 22:24
Thanks for helping to debug!

Ah, damnit, yeah, I forgot. Can't revoke a token with no client ID. I would like to ask you to please rotate / revoke that token ASAP if this is an account you care about, since it is, as mentioned, in the log.

As for the issue, thank you so much for the logs. I will have a look at the logs to see what date broke and how I can fix it.

**Comment by adbenitez** [comment] 2022-11-21 22:29
yes, realized too late that the log had sensitive info and that is why you asked to send it to your email :sweat_smile:

**Comment by halcy** [comment] 2022-11-21 22:34
Hm, seems it happens in the home timeline. I can't reproduce it on my akkoma account. I could, I guess, for now fix it such that when date parsing fails, we fall back to Jan 1st 1970, which will probably allow your bot to work fine.

**Comment by adbenitez** [comment] 2022-11-21 22:44
looking at the JSON that caused the error, I found this:

![image](https://user-images.githubusercontent.com/24558636/203172965-6555e505-1f19-460d-a233-2acb88441aea.png)

maybe it is that some toots in Pleroma have date fields with `null`???

**Comment by adbenitez** [comment] 2022-11-21 22:51
actually found one "created_at" with empty string:

![image](https://user-images.githubusercontent.com/24558636/203173851-99f1cd8e-facb-4ad4-892d-0484581ee783.png)

**Comment by halcy** [comment] 2022-11-21 23:12
ah, huh. Yeah, nothing to be done there except fill in a placeholder. Thanks!

**Comment by halcy** [comment] 2022-11-21 23:32
Now fixed in master. I will push a release sometime tomorrow, after that, when you update, problem should be fixed. Alternately, just drop a copy in your pythonpath, if you're in a hurry

**Closed by halcy** 2022-11-21 23:32 UTC
