### ISSUE TITLE
Any plans to support Pleroma

### ISSUE THREAD

**Issue by pla1** [halcy/Mastodon.py#163] opened 2019-04-14 21:14 UTC
Hi. 

I am using [Tootstream](https://github.com/magicalraccoon/tootstream) which uses Mastodon.py. Tootstream fails on replies with an error message of: `error while posting: ValueError`. I'm assuming it has something to do with Mastodon.py not handling [Pleroma's Flake IDs](https://git.pleroma.social/pleroma/pleroma/merge_requests/645). Any plans to support Pleroma? 

Thanks, [PLA](https://pla.social/pla)

**Comment by codl** [comment] 2019-04-15 01:12
Hi, welcome! Did you report the issue to tootstream's developers as well?

I don't have a pleroma instance to test this unfortunately, and a cursory look at the code didn't reveal anything that would fail like this

**Comment by craigmaloney** [comment] 2019-04-15 01:21
Yes, we're aware of it, and are following along if there's an update. I too am not on Pleroma, but from what I can tell it's an issue when translating the local ID to the global ID. 

The exception that we're getting is a ValueError, which is being captured in a generic exception when replying to a message. I've enclosed the screenshot that (hopefully) can point more to what's going on.

Thanks!

![6e55e60e037f07b2](https://user-images.githubusercontent.com/527251/56102448-214ce300-5efb-11e9-9079-b66673e96569.png)

**Comment by pla1** [comment] 2019-04-15 01:24
Holler if I can provide logs or testing. Thanks. ☮

**Comment by halcy** [comment] 2019-04-27 15:25
can anybody who uses pleroma comment on if codls patch fixed this (is now merged into master, not released yet)

**Comment by pla1** [comment] 2019-04-27 22:57
Not sure how to test. I did this hack. I replaced `/home/htplainf/projects/tootstream/lib/python3.6/site-packages/mastodon/Mastodon.py` with the contents of `https://raw.githubusercontent.com/halcy/Mastodon.py/master/mastodon/Mastodon.py`

I still get `error while posting: ValueError`.

**Comment by halcy** [comment] 2019-04-27 23:06
Bother. Guess

**Comment by pla1** [comment] 2019-04-27 23:07
@halcy https://pleroma.site has open registrations. Thanks!

**Comment by halcy** [comment] 2019-04-28 00:08
```
test_status = pleroma_api.toot("YO YO YO 2.0")
pleroma_api.status_reply(test_status, "test replY 2")
```

https://pleroma.site/notice/9iFUKvJ2HZ8hKFYyWm Works For Me(tm)

@craigmaloney can you try to get some more info what breaks, if anything, with tootstream if you use the Mastodon.py version currently in master?

**Comment by jfmcbrayer** [comment] 2019-04-29 12:18
Just for reference, https://github.com/jfmcbrayer/brutaldon is built on Mastodon.py, and everything that I've tested works with Pleroma. Maybe this is a tootstream bug?

**Comment by craigmaloney** [comment] 2019-04-29 12:55
Looks like we're not handling Pelroma's IDs properly:

"ValueError("invalid literal for int() with base 10: '9iIepfdIBfD8i0DZBo'",)"

I think we're doing explicit conversions of ints in there. Ugh. Please file a bug with tootstream and we'll take a peek 

Thanks!

**Comment by halcy** [comment] 2019-04-29 13:02
yeah, Mastodon.py does do this internally, but it does not throw an error if it fails:

https://github.com/halcy/Mastodon.py/blob/master/mastodon/Mastodon.py#L2511

I think the problem is here:

https://github.com/magicalraccoon/tootstream/blob/develop/src/tootstream/toot.py#L75

in tootstreams actual-id to display-id / user interface id translation. I'm pretty sure _map should be a dict in any case, using a list and .index seems like it'd make everything very slow eventually...

In any case, I think I can close this except I could maybe put some words in the documentation about how ids can be strings on pleroma (or we could just always return strings - but that might break a lot of code that already exists)

**Closed by halcy** 2019-04-29 13:02 UTC

**Comment by craigmaloney** [comment] 2019-04-29 13:04
Yeah, I've not dug too deeply into tootstream's mapping code (thus far it's worked) so will need to rip it apart and see what all is in there

**Comment by pla1** [comment] 2019-04-29 13:05
Created [Tootstream issue 208](https://github.com/magicalraccoon/tootstream/issues/208).
