### ISSUE TITLE
Version check fails when ran on Florence instance

### ISSUE THREAD

**Issue by Frinkel** [halcy/Mastodon.py#177] opened 2019-06-18 06:58 UTC
So I decided to move my bot instance to Florence earlier today, and realized all the bots I was running stopped posting once I did. I was confused at first, unsure as to exactly why, but then I gained more clarity when I tried running the script manually:
`mastodon.Mastodon.MastodonVersionError: Version check failed (Need version 1.0.0)`

Technically, Florence is running at around Mastodon 2.9.0, so it is definitely newer than vanilla Mastodon 1.0.0, but they use a completely different version numbering system which is currently at 0.0.1.0, which, of course, messes up the version check. I was able to fix this for myself by patching out the version check, but I'm sure that's probably not a good long-term viable solution, will probably have ramifications I haven't actually discovered yet, and I feel like other people are going to run into this same issue if the fork becomes more popular...

**Comment by halcy** [comment] 2019-06-18 07:07
Hm, does florence indicate in the instance response that it is florence? If not, oof. No real way around this other than disabling any version checking, which I would very strongly prefer not to. Where is their repo, anyways? Feel this issue should be cross-filed there, probably

**Comment by Frinkel** [comment] 2019-06-18 07:25
I'm not entirely sure, but looking at said Florence instance's page, where the version number would be it's just 0.0.1.0. (unlike, say, glitchsoc where it'd be version+glitch or something.)
That being said, their repo can be found [here](https://github.com/florence-social/mastodon-fork). I'm not 100% sure how to cross-file (as I haven't exactly used Github's issues tracker before tbh), is there a special way to do it, or would it just be making a new bug there and linking to this one?

**Comment by clarfon** [comment] 2019-06-19 01:22
Glitch-social doesn't actually keep track of its own version, which is why +glitch at the end of the version is good enough for them. For Florence we're going to want to actually track our own versions, but you're right that this shouldn't affect any existing Mastodon-compatible projects.

So, I'd say this is definitely not a bug here, but instead a bug with Florence-Mastodon instead.

**Comment by halcy** [comment] 2019-06-20 14:35
Seems like Florence will fix this so I will close it here. Florence is also adding a different field, which may be neat to document later on because it sounds like a good idea to have, but that's probably for after they have a stable release.

**Closed by halcy** 2019-06-20 14:35 UTC
