### ISSUE TITLE
Could not parse response as JSON, response code was 200 – Pixelfed

### ISSUE THREAD

**Issue by alex-ash** [halcy/Mastodon.py#242] opened 2022-07-21 19:54 UTC
Hello! I use Mastodon.py as a part of https://github.com/Horhik/Instagram2Fedi
Trying to parse images to Pixelfed.
Somehow it worked once and then I got the same error about JSON:

`Could not parse response as JSON, response code was 200, bad json content was 'b'<!DOCTYPE html>\n\n<html lang="en">\n<head>\n\t<meta charset="utf-8">\n\t<meta http-equiv="X-UA-Compatible" content="IE=edge">\n\t<meta name="viewport" content="width=device-width, initial-scale=1">\n\t<meta name="mobile-web-app-capable" content="yes">\n\n\t<title>pixelfed</title>\n\t<link rel="manifest" href="/manifest.json">\n\n\t<meta property="og:site_name" content="pixelfed">\n\t<meta property="og:title" content="pixelfed">\n\t<meta property="og:type" content="article">\n\t<meta property="og:url" content="https://pixelfed.social/login">\n\t\n\t<meta name="medium" content="image">\n\t<meta name="theme-color" content="#10c5f8">\n\t<meta name="apple-mobile-web-app-capable" content="yes">\n\t<link rel="shortcut icon" type="image/png" href="/img/favicon.png?v=2">\n\t<link rel="apple-touch-icon" type="image/png" href="/img/favicon.png?v=2">\n\t<link rel="canonical" href="https://pixelfed.social/login">\n\t<link href="/css/app.css?id=66c10c9502955c88d471277fface8c32" rel="stylesheet" data-stylesheet="light">\n\t<script type="text/javascript">window._sharedData = {curUser: {}, version: 0}; window.App = {config: {"open_registration":true,"uploader":{"max_photo_size":"15000","max_caption_length":"2000","album_limit":"10","image_quality":"85","max_collection_length":100,"optimize_image":true,"optimize_video":true,"media_types":"image\\/jpeg,image\\/gif,image\\/png,video\\/mp4,image\\/webp","enforce_account_limit":true},"activitypub":{"enabled":true,"remote_follow":true},"ab":{"lc":true,"rec":false,"loops":false,"top":false,"polls":false,"cached_public_timeline":true,"gps":false,"spa":true,"emc":true},"site":{"name":"pixelfed","domain":"pixelfed.social","url":"https:\\/\\/pixelfed.social","description":"The original Pixelfed instance, operated by the main developer @dansup"},"username":{"remote":{"formats":{"0":"@","1":"from","2":"custom"},"format":"@","custom":null}},"features":{"timelines":{"local":true,"network":true},"mobile_apis":true,"stories":true,"video":true,"import":{"instagram":false,"mastodon":false,"pixelfed":false},"label":{"covid":{"enabled":false,"org":"visit the WHO website","url":"https:\\/\\/www.who.int\\/emergencies\\/diseases\\/novel-coronavirus-2019\\/advice-for-public"}}}}};</script>\n\t</head>\n<body>\n\t<nav class="navbar navbar-expand navbar-light navbar-laravel shadow-none border-bottom sticky-top py-1">\n\t<div class="container">\n\t\t\t<a class="navbar-brand d-flex align-items-center" href="/" title="Logo">\n\t\t\t\t<img src="/img/pixelfed-icon-color.svg" height="30px" class="px-2" loading="eager" alt="Pixelfed logo">\n\t\t\t\t<span class="font-weight-bold mb-0 d-none d-sm-block" style="font-size:20px;">pixelfed</span>\n\t\t\t</a>\n\n\t\t\t<div class="collapse navbar-collapse">\n\t\t\t\n\t\t\t\n\t\t\t\t<ul class="navbar-nav ml-auto">\n\t\t\t\t\t<li>\n\t\t\t\t\t\t<a class="nav-link font-weight-bold text-dark" href="/login" title="Login">\n\t\t\t\t\t\t\tLogin\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t\t</ul>\n\t\t\t</div>\n\t</div>\n</nav>\n\t<main id="content">\n\t\t<div class="container mt-4">\n    <div class="row justify-content-center">\n        <div class="col-lg-5">\n            <div class="">\n                <div class="card-header bg-transparent p-3 text-center font-weight-bold h3">Login</div>\n\n                <div class="card-body">\n                    <form method="POST" action="https://pixelfed.social/login">\n                        <input type="hidden" name="_token" value="0PX5BL2deJHFCn0lF9xEyKNjd2S1I9heZjXSxIO9">\n                        <div class="form-group row">\n\n                            <div class="col-md-12">\n                                <input id="email" type="email" class="form-control" name="email" value="" placeholder="Email" required autofocus>\n\n                                                            </div>\n                        </div>\n\n                        <div class="form-group row">\n\n                            <div class="col-md-12">\n                                <input id="password" type="password" class="form-control" name="password" placeholder="Password" required>\n\n                                                            </div>\n                        </div>\n\n                        <div class="form-group row">\n                            <div class="col-md-12">\n                                <div class="checkbox">\n                                    <label>\n                                        <input type="checkbox" name="remember" > \n                                        <span class="font-weight-bold ml-1 text-muted">\n                                            Remember Me\n                                        </span>\n                                    </label>\n                                </div>\n                            </div>\n                        </div>\n\n                        \n                        <div class="form-group row mb-0">\n                            <div class="col-md-12">\n                                <button type="submit" class="btn btn-primary btn-block btn-lg font-weight-bold">\n                                    Login\n                                </button>\n\n                            </div>\n                        </div>\n                    </form>\n\n                    <hr>\n\n                    <p class="text-center font-weight-bold">\n                        <a href="https://pixelfed.social/password/reset">\n                            Forgot Password\n                        </a>\n                    </p>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>\n\t</main>\n\t<footer>\n    <div class="container py-5">\n        <p class="text-center text-uppercase font-weight-bold small text-justify">\n          <a href="https://pixelfed.social/site/about" class="text-dark p-2">About</a>\n          <a href="https://pixelfed.social/site/help" class="text-dark p-2">Help</a>\n          <a href="https://pixelfed.social/site/terms" class="text-dark p-2">Terms</a>\n          <a href="https://pixelfed.social/site/privacy" class="text-dark p-2">Privacy</a>\n          <a href="https://pixelfed.social/site/language" class="text-dark p-2">Language</a>\n        </p>\n        <p class="text-center text-muted small mb-0">\n          <span class="text-muted">\xc2\xa9 2022 pixelfed.social</span>\n          <span class="mx-2">\xc2\xb7</span>\n          <a href="https://pixelfed.org" class="text-muted font-weight-bold" rel="noopener">Powered by Pixelfed</a>\n          <span class="mx-2">\xc2\xb7</span>\n          <span class="text-muted">v0.11.3</span>\n        </p>\n    </div>\n  </footer>\n  \t<script type="text/javascript" src="/js/manifest.js?id=4e6dd9cb251d9698bfccb781db000cca"></script>\n\t<script type="text/javascript" src="/js/vendor.js?id=4b8baeff156b0f280596a985b98255bc"></script>\n\t<script type="text/javascript" src="/js/app.js?id=855c8b0847137dd56c72229ad305c032"></script>\n\t<script type="text/javascript" src="/js/components.js?id=35beb0748dd5518371686a5f00348fbf"></script>\n\t</body>\n</html>\n''
`

Mastodon.py version 1.5.1

**Comment by Snuggle** [comment] 2022-07-24 14:56
👋 Hello, @arittner and @alex-ash!

Here is [a minimum reproducible example](https://gist.github.com/Snuggle/265afddef76df0a2359f7daa9302aa53) I've created based on the original code also with an [output of the debug mode turned on](https://gist.github.com/Snuggle/4d483c8f25da4c56b60e60b5fb89592a).

```python
#!/usr/bin/env python3
import mastodon as Mastodon
import requests

url = "https://scontent-man2-1.cdninstagram.com/v/t51.2885-15/277617279_156833370081519_9214469682299031302_n.jpg?stp=dst-jpg_e35&_nc_ht=scontent-man2-1.cdninstagram.com&_nc_cat=103&_nc_ohc=FyVc-E5qEh4AX9c3zbW&edm=ALQROFkBAAAA&ccb=7-5&ig_cache_key=MjgwNjc5ODYwMjQ5MzUyNDU2Ng%3D%3D.2-ccb7-5&oh=00_AT9DpkEwL0mxwE96wyDdI5dSG9x5chWagcRtuLUGv0x1OA&oe=62E35860&_nc_sid=30a2ef"

print(Mastodon)
#Mastodon.Mastodon.create_app(
#    'snuggle_pixelfed',
#    api_base_url = 'https://pixelfed.social',
#    to_file = 'pytooter_clientcred.secret'
#)

mastodon = Mastodon.Mastodon(
    debug_requests = False,
    access_token = 'pytooter_usercred.secret',
    api_base_url = 'https://pixelfed.social'
)

def get_image(url):
    try:
        response = requests.get(url)
        response.raw.decode_content = True

        return response.content
    except Exception as e:
        print(e)
        
media = mastodon.media_post(media_file = get_image(url), mime_type = "image/jpeg")
print(media["id"])
```

The original error comes from: https://github.com/Horhik/Instagram2Fedi/blob/765e398010d467de9dfc0c5715c76629c26550c3/src/network.py#L46 when using https://pixelfed.social as the instance we are trying to post to.

**Comment by alex-ash** [comment] 2022-07-24 15:09
@Snuggle thank you so much! So the error on the github.com/Horhik/Instagram2Fedi, right?
I'm not a coder, that would be a nightmare for me to figure out, haha.
The strange part that worked for a couple of times last month when I tried to run it, so I don't know what to do now. Maybe it's a pixelfed.social new settings.

Any suggestions on what to do next to resolve?

PS tried to run with a new token and got the same error.

**Comment by arittner** [comment] 2022-07-24 16:29
Thank you @Snuggle for the code sample. I'll jump on it, ASAP.

**Comment by arittner** [comment] 2022-07-25 08:23
I have checked the pixelfed code and at this time I can't see that anything has changed on the endpoint. Also, the logic does not seem to have changed in the last year. The image is small enough.

And Mastodon.py has not changed anything about the media-upload in the last few years.

So, I need to create an account and test.

**Comment by arittner** [comment] 2022-07-25 10:31
Hm, I guess it's the login process, not the API itself. IMHO OAuth2 with `authorization_code` is not working.

**Comment by arittner** [comment] 2022-07-25 11:01
Ok, I created a user-access-token, but this token is IMHO not for `grant_type = authorization_code`. I get a BAD REQUEST (400). I guess this is the bearer token itself.

**Comment by arittner** [comment] 2022-07-25 11:49
It's working, so my first guess was valid: it's a login issue. 

If I check the sample response from the origin ticket, I see this in the html-code:

```html
...
<form method="POST" action="https://pixelfed.social/login">
  <input type="hidden" name="_token" value="0PX5BL2deJHFCn0lF9xEyKNjd2S1I9heZjXSxIO9">
  <div class="form-group row">

  <div class="col-md-12">\n <input id="email" type="email" class="form-control" name="email" value="" placeholder="Email" required autofocus>
...
```

This means, your login is not working. I guess, the access-token in your secret file is not any more valid and needs a refresh. But at the moment I am unsure if an automatic refresh is possible or if it is not reported correctly by pixelfed as an error. 

Anyway, please go to pixelfed, your profile, edit profile -> applications. Or use this link: https://pixelfed.social/settings/applications

Create a new token and use this token in your secret file (or as parameter for `access_token`). 

Then it should work.

But please remember: https://docs.pixelfed.org/technical-documentation/api-v1.html#authorization 

> OAuth Tokens will expire after 15 days, and must be refreshed after that

**Comment by Snuggle** [comment] 2022-07-25 22:37
Ahah, I found what was causing my issue! Gosh, I feel a bit silly as this was 100% user-error in my case.

I was going to pixelfed, your profile, edit profile -> _developers_, then creating an `oauth token` which gives a `40` character token and using that, which was causing the error above. ❌

After following your reply very carefully by going to edit profile -> _applications_, I created a `personal access token` which was `1,030` characters long (which seems oddly long to me, but oh well!) and used that instead. It worked! 🎉

### Solution
> Please go to pixelfed, your profile, edit profile -> applications. Or use this link: [pixelfed.social/settings/applications](https://pixelfed.social/settings/applications)

Thank you, @arittner, for your help figuring this out! Hopefully this solves the same issue for @alex-ash too.

**Comment by arittner** [comment] 2022-07-26 09:03
Hi @Snuggle 

I was also on different wrong paths because I'm not familiar with pixelfed. But yes, the `personal acess token` is the pure Bearer token. The OAuth2 handshake to receive a token by the different grant_type workflows are not supported / necessary. 

I'll close this issue.

**Closed by arittner** 2022-07-26 09:03 UTC
Labels: question
