### ISSUE TITLE
Can't post Media

### ISSUE THREAD

**Issue by NeuroWinter** [halcy/Mastodon.py#58] opened 2017-07-05 03:46 UTC
I am trying to post an image that is created by a script, how ever I cant seem to post it.
from the following code:
`
mastodon = mastodon_bot(botname, email, password, instance_url)
media = mastodon.media_post('newGif.gif')
postData = "Glitching #gifs all day " + media['url']
print(mastodon.status_post(postData ,None,media,None,'unlisted',"#glitchArt"))`

I get the following error message:

> {'error': 'Cannot attach more than 4 files'}

but I am only trying to attach one media file.

**Comment by halcy** [comment] 2017-08-16 09:13
Can you post a file that causes that? Your usage seems correct.

**Comment by vagabondsun** [comment] 2017-09-02 13:22
I believe I'm experiencing the same issue here, and it looks like it's because when I upload a file via media_post, the method returns a list of ~7 identical media dicts. 
I'm pretty sure I've traced the source of the problem to something in the __api_request() method, but that level of API stuff is way beyond my knowledge set so I can't really diagnose what's going on there. The info printed when debug_requests = true is similarly all greek to me but I can post that if it'd be helpful.

**Comment by halcy** [comment] 2017-09-05 13:59
That would be very helpful, and if it is certain files that always fail, it would also help if you could upload an example file somewhere.

**Comment by halcy** [comment] 2018-01-29 10:19
I'm going to close this as I cannot reproduce and it has just been sitting there, if anyone has a file that causes this please do feel free to reopen.

**Closed by halcy** 2018-01-29 10:19 UTC
